
377   format("-----this is an error identification-----",/, a)
920   format("-----Progress:",F6.2,"%-----")
      character*100 ini_infile_
      character*100 diag_infile_
      character*100 cld_mon_
      character*100 deltat_mon_
      character*100 prec_mon_
      character*100 rh_mon_
      character*100 temp_mon_
      character*100 trange_mon_
      character*100 wetd_mon_
      character*100 wspd_mon_
      character*100 soita_sand_
      character*100 soita_clay_
      character*100 vegtype_
      character*100 surta_
      character*100 topo_
      character*100 params_can_
      character*100 params_hyd_
      character*100 params_soi_
      character*100 params_veg_
      character*100 out_yearly_aet_
      character*100 out_yearly_biomass_
      character*100 out_yearly_co2fluxes_
      character*100 out_yearly_csoi_
      character*100 out_yearly_disturbf_
      character*100 out_yearly_exist_
      character*100 out_yearly_fcover_
      character*100 out_yearly_npp_
      character*100 out_yearly_nsoi_
      character*100 out_yearly_plai_
      character*100 out_yearly_runoff_
      character*100 out_yearly_sens_
      character*100 out_yearly_tsoi_
      character*100 out_yearly_vegtype0_
      character*100 out_yearly_wsoi_
      character*100 out_yearly_zcanopy_
      character*100 out_yearly_sapfrac_
      character*100 out_yearly_dummyv_
      character*100 out_yearly_solar_
      character*100 out_yearly_albedo_
      character*100 out_yearly_latent_
      character*100 out_yearly_totfall_
      character*100 out_yearly_clitw_
      character*100 out_yearly_csoislo_
      character*100 out_yearly_csoipas_
      character*100 out_monthly_aet_
      character*100 out_monthly_cloud_
      character*100 out_monthly_co2ratio_
      character*100 out_monthly_ir_
      character*100 out_monthly_lai_
      character*100 out_monthly_latent_
      character*100 out_monthly_npptot_
      character*100 out_monthly_qa_
      character*100 out_monthly_rain_
      character*100 out_monthly_rh_
      character*100 out_monthly_runoff_
      character*100 out_monthly_sens_
      character*100 out_monthly_snod_
      character*100 out_monthly_snof_
      character*100 out_monthly_snow_
      character*100 out_monthly_solar_
      character*100 out_monthly_temp_
      character*100 out_monthly_tsoi_
      character*100 out_monthly_wsoi_
      character*100 out_monthly_albedo_
      character*100 out_monthly_dummyv_
      character*100 out_daily_rain_
      character*100 out_daily_cloud_
      character*100 out_daily_rh_
      character*100 out_daily_snow_
      character*100 out_daily_aet_
      character*100 out_daily_trunoff_
      character*100 out_daily_srunoff_
      character*100 out_daily_drainage_
      character*100 out_daily_wsoi_
      character*100 out_daily_wisoi_
      character*100 out_daily_snod_
      character*100 out_daily_snof_
      character*100 out_daily_co2ratio_
      character*100 out_daily_co2mic_
      character*100 out_daily_templ_
      character*100 out_daily_zcanopy_
      character*100 out_daily_laicanopy_
      character*100 temp_danom_
      character*100 trange_danom_
      character*100 prec_danom_
      character*100 cld_danom_
      character*100 rh_danom_
      character*100 wspd_danom_
      character*100 wetd_danom_
      character*100 prec_daily_
      character*100 temp_daily_
      character*100 trange_daily_
      character*100 cld_daily_
      character*100 wspd_daily_
      character*100 sphum_daily_
      character*100 prec_fanom_
      character*100 trange_fanomc_
      character*100 wspd_fanomc_
	  character*100 sphum_fanom_
	  character*100 deltat_
	  character*100 out_global_
	  character*100 out_vegtype_
	  character*100 out_yearsrun_
	  character*100 out_diag_0_
	  character*100 out_diag_1_
	  character*100 out_diag_2_
	  character*100 out_diag_3_
	  character*100 out_diag_4_
	  character*100 out_diag_5_
	  character*100 out_diag_6_
	  character*100 out_diag_7_
	  character*100 out_diag_8_
	  character*100 out_diag_9_
      real progress_

c


      common /inifiles/  ini_infile_,
     >   diag_infile_,
     >   cld_mon_,
     >   deltat_mon_,
     >   prec_mon_,
     >   rh_mon_,
     >   temp_mon_,
     >   trange_mon_,
     >   wetd_mon_,
     >   wspd_mon_,
     >   soita_sand_,
     >   soita_clay_,
     >   vegtype_,
     >   surta_,
     >   topo_,
     >   params_can_,
     >   params_hyd_,
     >   params_soi_,
     >   params_veg_,
     >   out_yearly_aet_,
     >   out_yearly_biomass_,
     >   out_yearly_co2fluxes_,
     >   out_yearly_csoi_,
     >   out_yearly_disturbf_,
     >   out_yearly_exist_,
     >   out_yearly_fcover_,
     >   out_yearly_npp_,
     >   out_yearly_nsoi_,
     >   out_yearly_plai_,
     >   out_yearly_runoff_,
     >   out_yearly_sens_,
     >   out_yearly_tsoi_,
     >   out_yearly_vegtype0_,
     >   out_yearly_wsoi_,
     >   out_yearly_zcanopy_,
     >   out_yearly_sapfrac_,
     >   out_yearly_dummyv_,
     >   out_yearly_solar_,
     >   out_yearly_albedo_,
     >   out_yearly_latent_,
     >   out_yearly_totfall_,
     >   out_yearly_clitw_,
     >   out_yearly_csoislo_,
     >   out_yearly_csoipas_,
     >   out_monthly_aet_,
     >   out_monthly_cloud_,
     >   out_monthly_co2ratio_,
     >   out_monthly_ir_,
     >   out_monthly_lai_,
     >   out_monthly_latent_,
     >   out_monthly_npptot_,
     >   out_monthly_qa_,
     >   out_monthly_rain_,
     >   out_monthly_rh_,
     >   out_monthly_runoff_,
     >   out_monthly_sens_,
     >   out_monthly_snod_,
     >   out_monthly_snof_,
     >   out_monthly_snow_,
     >   out_monthly_solar_,
     >   out_monthly_temp_,
     >   out_monthly_tsoi_,
     >   out_monthly_wsoi_,
     >   out_monthly_albedo_,
     >   out_monthly_dummyv_,
     >   out_daily_rain_,
     >   out_daily_cloud_,
     >   out_daily_rh_,
     >   out_daily_snow_,
     >   out_daily_aet_,
     >   out_daily_trunoff_,
     >   out_daily_srunoff_,
     >   out_daily_drainage_,
     >   out_daily_wsoi_,
     >   out_daily_wisoi_,
     >   out_daily_snod_,
     >   out_daily_snof_,
     >   out_daily_co2ratio_,
     >   out_daily_co2mic_,
     >   out_daily_templ_,
     >   out_daily_zcanopy_,
     >   out_daily_laicanopy_,
     >   out_diag_0_,
     >   out_diag_1_,
     >   out_diag_2_,
     >   out_diag_3_,
     >   out_diag_4_,
     >   out_diag_5_,
     >   out_diag_6_,
     >   out_diag_7_,
     >   out_diag_8_,
     >   out_diag_9_,
     >	 out_global_,
     >	 out_vegtype_,
     >	 out_yearsrun_,
     >   temp_danom_,
     >   trange_danom_,
     >   prec_danom_,
     >   cld_danom_,
     >   rh_danom_,
     >   wspd_danom_,
     >   wetd_danom_,
     >   prec_daily_,
     >   temp_daily_,
     >   trange_daily_,
     >   cld_daily_,
     >   wspd_daily_,
     >   sphum_daily_,
     >   prec_fanom_,
     >   trange_fanomc_,
     >	 wspd_fanomc_,
     >   deltat_,
     >   sphum_fanom_,
     >   progress_

